# -*- coding: utf-8 -*-
"""BU_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_m8Hv2xE5NcR4oDS3vvTgJDj5VlW9QR2
"""

import nltk
import json
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import random
import warnings
warnings.filterwarnings('ignore')

intents = {
    "intents": [
  {
    "tag": "bennett_admissions_process",
    "patterns": [
      "What is the admission process for Bennett University?",
      "How can I apply to Bennett?",
      "Tell me the steps for admission.",
      "What documents are needed for application?",
      "Is there an entrance exam?",
      "How does the selection process work?"
    ],
    "responses": [
      "Apply by filling the online application form on the official Bennett University admissions portal. Selection is primarily merit-based and may consider Class XII scores, national exam scores (where applicable, e.g., JEE Main, SAT, CUET), and/or Bennett’s own entrance tests (such as BUDAT/BUMAT/BULAT) depending on the program. Some programs include personal interviews or portfolio reviews. Required documents typically include mark-sheets, photo ID, passport-size photo, and any exam scorecards — check the admissions page for the exact document list for your program."
    ]
  },
  {
    "tag": "bennett_admission_deadline",
    "patterns": [
      "When is the last date to apply?",
      "What is the application deadline for 2025?",
      "Are admissions for 2025 open?",
      "Can I still apply?",
      "When do admissions close?"
    ],
    "responses": [
      "The application deadline for the 2025 academic year is September 30, 2025. It is recommended to apply early since seats may be allocated on a rolling / first-come basis; always confirm current deadlines on the official admissions page."
    ]
  },
  {
    "tag": "bennett_schools",
    "patterns": [
      "What are the different schools at Bennett University?",
      "Which departments do you have?",
      "Tell me about the academic schools.",
      "What fields of study are offered?"
    ],
    "responses": [
      "Bennett University comprises multiple schools, including the School of Engineering & Applied Sciences (and related engineering disciplines), School of Management, Times School of Media, School of Law, School of Design, School of Liberal Arts, and specialized schools for AI and other emerging areas. Each school hosts undergraduate, postgraduate, and research programs — see the Academics/Schools section on the site for program-wise details."
    ]
  },
  {
    "tag": "bennett_btech_courses",
    "patterns": [
      "What B.Tech specializations are available?",
      "Which engineering courses do you offer?",
      "Can I study AI at Bennett?",
      "Tell me about the B.Tech in Computer Science.",
      "What are the options in the School of Engineering?"
    ],
    "responses": [
      "The School of Engineering offers B.Tech degrees and related undergraduate programs such as Computer Science (CSE), Artificial Intelligence (AI), Electronics & Communication (ECE), Mechanical Engineering, Biotechnology, and Engineering Physics. Additional specializations and elective tracks include Data Science, Cyber Security, Robotics, Gaming, and Drones among others. Check the specific program pages for seat intake and curriculum."
    ]
  },
  {
    "tag": "bennett_management_courses",
    "patterns": [
      "Do you have an MBA program?",
      "What are the management courses?",
      "Tell me about the BBA program.",
      "What specializations are offered in the MBA?"
    ],
    "responses": [
      "Yes — Bennett’s School of Management offers undergraduate (BBA) and postgraduate (MBA) programs. MBA specializations and elective areas include Marketing, Finance, Human Resources, Business Analytics, Media Management, and Logistics & Supply Chain Management. Program details and admission requirements are available on the Management school pages."
    ]
  },
  {
    "tag": "bennett_law_courses",
    "patterns": [
      "What law programs are available?",
      "Do you offer an integrated law degree?",
      "Tell me about the School of Law.",
      "Is Bennett a good university for law?"
    ],
    "responses": [
      "The School of Law offers integrated undergraduate law programs such as B.A. LL.B. (Hons.) and BBA LL.B. (Hons.), as well as postgraduate (LL.M.) and Ph.D. research programs. The School is designed to meet Bar Council of India norms; check curriculum, faculty, and placement specifics on the School of Law page to see fit for your goals."
    ]
  },
  {
    "tag": "bennett_placements",
    "patterns": [
      "How are the placements at Bennett University?",
      "What is the average package?",
      "Which companies recruit from Bennett?",
      "Tell me about the placement record for B.Tech.",
      "What was the highest package offered?"
    ],
    "responses": [
      "Bennett University reports strong placement outcomes. For B.Tech, the highest domestic package reported has reached ₹1.37 Crore PA with an average around ₹11.10 LPA. For MBA, recent placement reports show a highest package of ₹33 LPA and an average of approximately ₹7.41 LPA. Over 450 organizations participate in campus hiring across programs—refer to the official Placements page for year-wise and program-wise breakdowns."
    ]
  },
  {
    "tag": "bennett_recruiters",
    "patterns": [
      "Who are the top recruiters?",
      "Which major companies visit the campus for placements?",
      "Can you name some of the companies that hire from Bennett?"
    ],
    "responses": [
      "A large and diverse set of national and multinational companies recruit from Bennett across sectors (IT, product, consulting, finance, media, manufacturing, etc.). The placement/placement-partners page on the official site publishes an up-to-date list of visiting recruiters and role categories — please consult that page for the detailed and current list."
    ]
  },
  {
    "tag": "bennett_hostel_facilities",
    "patterns": [
      "Is there a hostel on campus?",
      "What are the hostel facilities like?",
      "Tell me about the accommodation.",
      "Are the hostels air-conditioned?",
      "What is the hostel fee?"
    ],
    "responses": [
      "Yes — Bennett provides modern on-campus hostels and collaborates with off-campus partners (e.g., Nalanda Living). Rooms are generally furnished and air-conditioned; standard facilities include mess/cafeteria, common areas, security, and utilities. Hostel fees vary by occupancy: on-campus triple sharing is approximately ₹1,70,000 per annum, while Nalanda (off-campus) triple is shown around ₹1,50,000 per annum. Single and twin options are higher (single reported around ₹3,24,000 PA and twin around ₹2,10,000 PA in fee tables). Always confirm the exact room type and current fees from the Fees/Hostel page."
    ]
  },
  {
    "tag": "bennett_student_clubs",
    "patterns": [
      "What student clubs are there?",
      "How is the campus life?",
      "Are there extracurricular activities?",
      "Can I join a music or drama club?",
      "What is there to do outside of academics?"
    ],
    "responses": [
      "Campus life at Bennett is active with numerous student-run clubs and societies across music, drama, dance, gaming, comedy, technology, entrepreneurship, and social causes. Examples include music and dramatics societies and several technical and cultural clubs — students can join clubs based on interest and participate in events, fests, and competitions. See the student activities / clubs section for an updated list."
    ]
  },
  {
    "tag": "bennett_fee_structure",
    "patterns": [
      "How much is the fee for B.Tech?",
      "What is the fee structure for the MBA program?",
      "Can you give me the details of the tuition fees?",
      "Is there a registration fee?"
    ],
    "responses": [
      "Fees vary by program and year. For example, the first-year fee for B.Tech (CSE) is reported as ₹4,25,000, which includes a one-time registration charge of ₹45,000. The fee pages list program-wise tuition, registration, refundable deposits, and other charges (hostel, mess, security). For exact, program-specific breakdowns and the latest updates, consult the official Fee Structure page."
    ]
  },
  {
    "tag": "bennett_scholarships",
    "patterns": [
      "Does Bennett University offer scholarships?",
      "How can I get a scholarship?",
      "What are the eligibility criteria for scholarships?",
      "Is there a scholarship for a single girl child?"
    ],
    "responses": [
      "Yes — Bennett offers merit-based scholarships for incoming students (based on Class XII, IB, or SAT scores where applicable) and academic scholarships for continuing students based on CGPA. The university also maintains specific policies for categories such as single girl child and wards of defense personnel. Eligibility criteria, scholarship percentages, and application procedures are detailed on the Scholarships / Financial Aid page."
    ]
  },
  {
    "tag": "bennett_contact",
    "patterns": [
      "How can I contact Bennett University?",
      "What is the university's address?",
      "Is there a contact number for admissions?",
      "Where is Bennett University located?"
    ],
    "responses": [
      "Bennett University is located at Plot Nos. 8–11, TechZone II, Greater Noida, Uttar Pradesh (Pin code 201310). For admissions assistance you can call the toll-free number 1800-103-8484; other contact details (departmental phone numbers and email IDs) are available on the Contact Us page of the official website."
    ]
  }
]
}

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

stemmer = WordNetLemmatizer()

words = []
classes = []
documents = []
ignore_words = ['?']


for intent in intents['intents']:
    for pattern in intent['patterns']:
        # Tokenize each word in the sentence
        w = nltk.word_tokenize(pattern)
        # Add to our words list
        words.extend(w)
        # Add to documents in our corpus
        documents.append((w, intent['tag']))
        # Add to our classes list
        if intent['tag'] not in classes:
            classes.append(intent['tag'])


words = [stemmer.lemmatize(w.lower()) for w in words if w not in ignore_words]
words = sorted(list(set(words)))


classes = sorted(list(set(classes)))

print(len(documents), "documents")
print(len(classes), "classes", classes)
print(len(words), "unique lemmatized words", words)

training = []
output = []
output_empty = [0] * len(classes)

# Training set, bag of words for each sentence
for doc in documents:
    # Initialize our bag of words
    bag = []
    # List of tokenized words for the pattern
    pattern_words = doc[0]
    # Lemmatize each word
    pattern_words = [stemmer.lemmatize(word.lower()) for word in pattern_words]
    # Create our bag of words array
    for w in words:
        bag.append(1) if w in pattern_words else bag.append(0)

    # Output is a '0' for each tag and '1' for the current tag
    output_row = list(output_empty)
    output_row[classes.index(doc[1])] = 1

    training.append([bag, output_row])

random.shuffle(training)


def synonym_replacement(tokens, limit):
    augmented_sentences = []
    for i in range(len(tokens)):
        synonyms = []
        for syn in wordnet.synsets(tokens[i]):
            for lemma in syn.lemmas():
                synonyms.append(lemma.name())
        if len(synonyms) > 0:
            num_augmentations = min(limit, len(synonyms))
            sampled_synonyms = random.sample(synonyms, num_augmentations)
            for synonym in sampled_synonyms:
                augmented_tokens = tokens[:i] + [synonym] + tokens[i + 1:]
                augmented_sentences.append(' '.join(augmented_tokens))
    return augmented_sentences


# Augment the training data using synonym replacement
augmented_data = []
limit_per_tag = 100

for i, doc in enumerate(training):
    bag, output_row = doc
    tokens = [words[j] for j in range(len(words)) if bag[j] == 1]
    augmented_sentences = synonym_replacement(tokens, limit_per_tag)
    for augmented_sentence in augmented_sentences:
        augmented_bag = [1 if augmented_sentence.find(word) >= 0 else 0 for word in words]
        augmented_data.append([augmented_bag, output_row])


# combined_data = np.concatenate((training, augmented_data), axis=0)
combined_data = training + augmented_data
random.shuffle(combined_data)

random.shuffle(combined_data)

from sklearn.model_selection import train_test_split


def separate_data_by_tags(data):
    data_by_tags = {}
    for d in data:
        tag = tuple(d[1])
        if tag not in data_by_tags:
            data_by_tags[tag] = []
        data_by_tags[tag].append(d)
    return data_by_tags.values()


separated_data = separate_data_by_tags(combined_data)

# Lists to store training and testing data
training_data = []
testing_data = []

# Split each tag's data into training and testing sets
for tag_data in separated_data:
    train_data, test_data = train_test_split(tag_data, test_size=0.2, random_state=42)
    training_data.extend(train_data)
    testing_data.extend(test_data)


random.shuffle(training_data)
random.shuffle(testing_data)

# Convert training and testing data back to np.array
train_x = np.array([d[0] for d in training_data])
train_y = np.array([d[1] for d in training_data])
test_x = np.array([d[0] for d in testing_data])
test_y = np.array([d[1] for d in testing_data])

class NeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu1 = nn.ReLU()
        self.bn1 = nn.BatchNorm1d(hidden_size)
        self.dropout1 = nn.Dropout(0.2)

        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.relu2 = nn.ReLU()
        self.bn2 = nn.BatchNorm1d(hidden_size)
        self.dropout2 = nn.Dropout(0.2)

        self.fc3 = nn.Linear(hidden_size, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.bn1(x)
        x = self.dropout1(x)

        x = self.fc2(x)
        x = self.relu2(x)
        x = self.bn2(x)
        x = self.dropout2(x)

        x = self.fc3(x)
        output = self.softmax(x)
        return output

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return self.softmax(x)

class CustomDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

def accuracy(predictions, targets):
    predicted_labels = torch.argmax(predictions, dim=1)
    true_labels = torch.argmax(targets, dim=1)
    correct = (predicted_labels == true_labels).sum().item()
    total = targets.size(0)
    return correct / total

def test_model(model, test_loader, criterion):
    model.eval()
    total_loss = 0.0
    total_accuracy = 0.0
    num_batches = len(test_loader)

    with torch.no_grad():
        for inputs, targets in test_loader:
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            total_loss += loss.item() * inputs.size(0)
            total_accuracy += accuracy(outputs, targets) * inputs.size(0)

    average_loss = total_loss / len(test_loader.dataset)
    average_accuracy = total_accuracy / len(test_loader.dataset)
    return average_loss, average_accuracy

# Create DataLoader for training and testing data
train_x = torch.tensor(train_x).float()
train_y = torch.tensor(train_y).float()
test_x = torch.tensor(test_x).float()
test_y = torch.tensor(test_y).float()

batch_size = 64
train_dataset = CustomDataset(train_x, train_y)
test_dataset = CustomDataset(test_x, test_y)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Define the model, loss function, and optimizer
input_size = len(train_x[0])
hidden_size = 8
output_size = len(train_y[0])
model = NeuralNetwork(input_size, hidden_size, output_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

# Train the model and evaluate on the testing set
num_epochs = 50
for epoch in range(num_epochs):
    # Training
    model.train()
    running_loss = 0.0
    running_acc = 0.0
    for inputs, targets in train_loader:
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, targets)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Update statistics
        running_loss += loss.item() * inputs.size(0)
        running_acc += accuracy(outputs, targets) * inputs.size(0)

    # Calculate average training loss and accuracy for the epoch
    epoch_loss = running_loss / len(train_loader.dataset)
    epoch_acc = running_acc / len(train_loader.dataset)

    # Print training loss and accuracy for each epoch
    print(f"Epoch [{epoch+1}/{num_epochs}], Training Loss: {epoch_loss:.4f}, Training Accuracy: {epoch_acc:.4f}")

    # Evaluate on the testing set
    test_loss, test_accuracy = test_model(model, test_loader, criterion)
    print(f"Epoch [{epoch+1}/{num_epochs}], Testing Loss: {test_loss:.4f}, Testing Accuracy: {test_accuracy:.4f}")

# Save the trained model
torch.save(model.state_dict(), 'model.pth')

def load_model(model_path, input_size, hidden_size, output_size):
    model = NeuralNetwork(input_size, hidden_size, output_size)
    model.load_state_dict(torch.load(model_path))
    model.eval()
    return model

# Function to preprocess the input sentence
def preprocess_sentence(sentence, words):
    sentence_words = sentence.lower().split()
    sentence_words = [word for word in sentence_words if word in words]
    return sentence_words

# Function to convert the preprocessed sentence into a feature vector
def sentence_to_features(sentence_words, words):
    features = [1 if word in sentence_words else 0 for word in words]
    return torch.tensor(features).float().unsqueeze(0)

# Function to generate a response using the trained model
def generate_response(sentence, model, words, classes):
    sentence_words = preprocess_sentence(sentence, words)
    if len(sentence_words) == 0:
        return "I'm sorry, but I don't understand. Can you please rephrase or provide more information?"

    features = sentence_to_features(sentence_words, words)
    with torch.no_grad():
        outputs = model(features)

    probabilities, predicted_class = torch.max(outputs, dim=1)
    confidence = probabilities.item()
    predicted_tag = classes[predicted_class.item()]

    if confidence > 0.5:
        for intent in intents['intents']:
            if intent['tag'] == predicted_tag:
                return random.choice(intent['responses'])

    return "I'm sorry, but I'm not sure how to respond to that."

model_path = 'model.pth'
input_size = len(words)
hidden_size = 8
output_size = len(classes)
model = load_model(model_path, input_size, hidden_size, output_size)

# Test the chatbot response
# print('Hello! I am a chatbot. How can I help you today? Type "quit" to exit.')
# while True:
#     user_input = input('> ')
#     if user_input.lower() == 'quit':
#         break
#     response = generate_response(user_input, model, words, classes)
#     print(response)

# ... (all your model/model loading code here)

# CLI loop must be under if __name__ == "__main__"
# Existing model loading code here...

# Only run CLI loop if direct run (not import)
if __name__ == "__main__":
    print('Hello! I am a chatbot.')
    while True:
        user_input = input('> ')
        if user_input.lower() == 'quit':
            break
        response = generate_response(user_input, model, words, classes)
        print(response)


import textwrap

test_cases = [
    "Hello",
    "Good Morning",
    "What are you",
    "Who Created You",
    "Thats not right",
    "What are the class sizes like?",
    "Does your major require an independent study?",
    "Are professors available for research with students?",
    "Are there study abroad programs available?",
    "What's it like to be a first-year student here?",
    "Can students spend a semester abroad?",
    "How can I get involved in research at your college?",
    "Tell me about the extracurricular activities on campus.",
    "What resources are available for career counseling and job placement?",
    "Does the school offer any scholarships or financial aid for international students?",
    "How does the campus support students with disabilities?",
    "Are there any on-campus housing options for upperclassmen?",
    "What opportunities are there for students interested in community service and volunteering?",
    "Is there a mentoring program for freshmen to help with their transition to college life?",
    "What type of on-campus dining options are available?",
    "Tell me about the campus safety measures and security services.",
    "What type of technology and computer facilities are accessible to students?",
    "Are there any notable guest speakers or events that regularly occur on campus?",
    "How does the college foster a sense of community and inclusivity among students?",
    "What is the average student-to-faculty ratio at the university?",
    "Can students participate in sports or fitness activities even if they are not part of a varsity team?",
    "Are there any unique academic programs or centers of excellence at the college?",
    "What type of student organizations are available for students to join?",
    "Tell me about the college's commitment to sustainability and environmental initiatives.",
    "How does the college handle academic support and tutoring for students who need extra help?",
    "Are there any opportunities for students to showcase their artistic talents, such as theater performances or art exhibitions?",
    "Does the college have any partnerships with local businesses or organizations for internships and experiential learning?",
    "What are the on-campus recreational facilities, such as fitness centers or sports fields?",
    "What are the admission requirements for international students?",
    "Can you tell me about the campus facilities, such as the library and student center?",
    "What types of student support services are available, such as counseling and health services?",
    "How diverse is the student body on campus?",
    "What are the top academic programs offered at the college?",
    "Does the college have any special programs for first-generation college students?",
    "What is the college's policy on AP credits and advanced placement?",
    "Are there opportunities for undergraduate students to participate in research with faculty?",
    "What kind of financial aid packages are available for low-income students?",
    "Can you provide information on the college's alumni network and career connections?",
    "Tell me about the college's approach to experiential learning and internships.",
    "What are the campus housing options for students who prefer a single room?",
    "Does the college offer any honors or honors programs for high-achieving students?",
    "What are the popular social events and traditions on campus?",
    "How does the college support students in finding part-time jobs while studying?",
    "Can you tell me more about the college's study abroad partnerships and locations?",
    "What is the college's policy on transfer credits?",
    "Are there any special resources or clubs for students interested in entrepreneurship?",
    "Tell me about the college's sustainability initiatives and green campus efforts.",
    "How accessible are professors for office hours and academic support?",
    "What are the research opportunities available for undergraduate students?",
    "Can you provide information on the college's campus safety statistics and measures?",
    "How does the college celebrate diversity and promote inclusivity on campus?",
    "What are the available options for transportation to and from campus?",
    "Tell me about the college's alumni mentoring programs and career networking events.",
    "Are there any leadership development programs or student government opportunities?",
    "How does the college handle academic advising and course registration for new students?",
    "What are the college's facilities for performing arts and music?",
    "Can you provide information on the college's community service requirements?",
    "Tell me about the college's approach to experiential learning and internships.",
    "What are the campus housing options for students who prefer a single room?",
    "Does the college offer any honors or honors programs for high-achieving students?",
    "What are the popular social events and traditions on campus?",
    "How does the college support students in finding part-time jobs while studying?",
    "Can you tell me more about the college's study abroad partnerships and locations?",
    "What is the college's policy on transfer credits?",
    "Are there any special resources or clubs for students interested in entrepreneurship?",
    "Tell me about the college's sustainability initiatives and green campus efforts.",
    "How accessible are professors for office hours and academic support?",
    "What are the research opportunities available for undergraduate students?",
    "Can you provide information on the college's campus safety statistics and measures?",
    "How does the college celebrate diversity and promote inclusivity on campus?",
    "What are the available options for transportation to and from campus?",
    "Tell me about the college's alumni mentoring programs and career networking events.",
    "Are there any leadership development programs or student government opportunities?",
    "How does the college handle academic advising and course registration for new students?",
    "What are the college's facilities for performing arts and music?",
    "Can you provide information on the college's community service requirements?",
]
print('Testing Cases starting..........\n')

unseen = []
for i in test_cases:
  print(i)
  print('\n')
  text = generate_response(i.lower(),model, words, classes)
  print(textwrap.fill(text, width=70))
  print('-------------------------------------')
  if text == "I'm sorry, but I'm not sure how to respond to that.":
    unseen.append(i)

['Thats not right',
 'What are the class sizes like?',
 'Can students spend a semester abroad?',
 'What type of student organizations are available for students to join?',
 'Are there opportunities for undergraduate students to participate in research with faculty?',
 "Can you provide information on the college's campus safety statistics and measures?",
 'What are the available options for transportation to and from campus?',
 "Can you provide information on the college's campus safety statistics and measures?",
 'What are the available options for transportation to and from campus?']



